wandb_version: 1

batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
hidden_size:
  desc: null
  value: 512
max_epochs:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709651501.437266
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      3:
      - 2
      - 16
      - 23
      4: 3.11.7
      5: 0.16.3
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
